micronaut:
  application:
    name: micronaut-predator

jackson:
  bean-introspection-module: true

datasources:
  default:
    url: jdbc:postgresql://0.0.0.0:5432/predator?ssl=false
    driverClassName: org.postgresql.Driver
    username: predator
    password: predator123
#    schema-generate: CREATE_DROP
#    dialect: H2

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true